[programs.localnet]
jet_governance = "5TBwvU5xoA13fzmZgWVgFBUmBz1YCdiq2AshDZpPn3AL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/drew/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
