anchor_version = "0.26.0"
solana_version = "1.14.16"

[programs.localnet]
jet_auth = "JPALXR88jy2fG3miuu4n3o8Jef4K2Cgc3Uypr3Y8RNX"
jet_rewards = "JET777rQuPU8BatFbhp6irc1NAbozxTheBqNo25eLQP"
jet_staking = "JPLockxtkngHkaQT5AuRYow3HyUv5qWzmhwsCPd653n"
jet_vote_batcher = "EaK4h4qn9BDoA5taao5F5E3E3MK4HKzhV9EnVsqYr5oJ"

[programs.mainnet]
jet_auth = "JPALXR88jy2fG3miuu4n3o8Jef4K2Cgc3Uypr3Y8RNX"
jet_rewards = "JET777rQuPU8BatFbhp6irc1NAbozxTheBqNo25eLQP"
jet_staking = "JPLockxtkngHkaQT5AuRYow3HyUv5qWzmhwsCPd653n"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "JPGov2SBA6f7XSJF5R4Si5jEJekGiyrwP2m7gSEqLUs"
program = "./deps/spl_governance.so"


[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
