name: Devnet Deployment

on:
  push:
    branches: [master]
    paths:
      - 'programs/**/*.rs'
      - 'programs/**/*.toml'
  workflow_dispatch: {}

env:
  ANCHOR_CLI_VERSION: 0.19.0
  SOLANA_CLI_VERSION: 1.9.2

defaults:
  run:
    shell: bash

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: cache-deps
        name: Cache Dependency Paths
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            /usr/local/lib/node_modules
            /usr/local/bin/anchor
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana
            ./target/

      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get -y install pkg-config build-essential libudev-dev

      - name: Install Rust
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Solana
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"

      - name: Setup NPM
        uses: actions/setup-node@v2

      - name: Install Anchor CLI
        run: npm i -g @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}

  build:
    name: Build Programs
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: cache-deps
        name: Cache Dependency Paths
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            /usr/local/lib/node_modules
            /usr/local/bin/anchor
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana
            ./target/

      - name: Update PATH
        run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
          
      - name: Build Programs
        run: anchor build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [install, build]
    steps:
      - id: cache-deps
        name: Cache Dependency Paths
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            /usr/local/lib/node_modules
            /usr/local/bin/anchor
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana
            ./target/
      
      - name: Setup Environment
        run: |
          echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV \
          && mkdir ~/.config/solana \
          && echo ${{ secrets.SOLANA_DEVNET_DEPLOYER_KEYPAIR }} > ~/.config/solana/deployer.json

      - name: Deploy Rewards
        run: anchor deployer --program-name rewards --provider.cluster devnet --provider.wallet ~/.config/solana/deployer.json

      - name: Deploy Staking
        run: anchor deployer --program-name staking --provider.cluster devnet --provider.wallet ~/.config/solana/deployer.json
