name: Devnet Deployment

on:
  push:
    branches: [master]
    paths:
      - 'programs/**/*.rs'
      - 'programs/**/*.toml'
  workflow_dispatch: {}

env:
  ANCHOR_CLI_VERSION: 0.19.0
  SOLANA_CLI_VERSION: 1.9.2

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Install Dependencies and Build Programs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana/
            ./target/

      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get -y install pkg-config build-essential libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"

      - name: Setup NPM
        uses: actions/setup-node@v2

      - name: Install Anchor CLI
        run: npm i -g @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}

      - name: Update Environment
        run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - name: Build Rewards and Staking
        run: anchor build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Recover Cache
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-a${{ env.ANCHOR_CLI_VERSION }}-s${{ env.SOLANA_CLI_VERSION }}
          path: |
            ~/.cache/solana
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/solana/
            ./target/

      - name: Setup NPM
        uses: actions/setup-node@v2

      - name: Install Anchor CLI
        run: npm i -g @project-serum/anchor-cli@${{ env.ANCHOR_CLI_VERSION }}
      
      - name: Setup Environment
        run: |
          echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV \
          && mkdir ~/.config/solana \
          && echo ${{ secrets.SOLANA_DEVNET_DEPLOYER_KEYPAIR }} > ~/.config/solana/deployer.json \
          && echo ${{ secrets.REWARDS_DEVNET_KEYPAIR }} > target/deploy/jet_rewards-keypair.json \
          && echo ${{ secrets.STAKING_DEVNET_KEYPAIR }} > target/deploy/jet_staking-keypair.json

      - name: Deploy Rewards
        run: anchor deployer --program-name rewards --provider.cluster devnet --provider.wallet ~/.config/solana/deployer.json

      - name: Deploy Staking
        run: anchor deployer --program-name staking --provider.cluster devnet --provider.wallet ~/.config/solana/deployer.json
