name: Lint

on: [push]

defaults:
  run:
    shell: bash

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Prettier Check
        run: npm ci && npm run fmt

      - name: ESLint Check
        run: npm run lint

  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Cargo Format Check
        run: cargo fmt --all --check && cargo clippy -- -Dwarnings
