name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  ANCHOR_CLI_VERSION: 0.23.0
  NODE_VERSION: 17.7.1
  SOLANA_CLI_VERSION: 1.9.13

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Prettier Check
        run: npm ci && npm run fmt

      - name: ESLint Check
        run: npm run lint

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Cache Cargo
        uses: actions/cache@v2
        id: cache-cargo-build
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ./target
          key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Format Check
        run: cargo fmt --all --check

      - name: Clippy Check
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Cargo Test
        run: cargo test

  setup-anchor:
    name: Setup Anchor
    runs-on: ubuntu-latest
    needs: [typescript, rust]
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Cache Cargo
        uses: actions/cache@v2
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-anchor-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Anchor
        run: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_CLI_VERSION }} anchor-cli --locked --force

      - uses: actions/upload-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/anchor

  anchor-test:
    name: Anchor Test
    runs-on: ubuntu-latest
    needs: [setup-anchor]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/

      - run: chmod +rwx ~/.cargo/bin/anchor
      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Cache Solana
        uses: actions/cache@v2
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}

      - name: Install Solana Tools
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"

      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: solana-keygen new --no-bip39-passphrase
      - run: solana config set --url localhost

      - name: Install Nodejs
        uses: actions/setup-node@v2

      - uses: actions/cache@v2
        name: Cache Node Modules
        id: cache-typescript-node-modules
        with:
          path: |
            ./ts/node_modules/
          key: solana-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Run Anchor Test
        run: npm ci && anchor test
